# Copyright 2025 The Khronos Group Inc.
# Copyright 2025 Valve Corporation
# Copyright 2025 LunarG, Inc.
#
# SPDX-License-Identifier: Apache-2.0

name: Run codegen

on:
  workflow_dispatch:

jobs:
  run_codegen:
    name: Run codegen
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
            python-version: '3.12'

      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Update known_good.json dependencies
        run: python scripts/update_known_good.py

      - name: Generate source
        run: |
          scripts/update_deps.py --dir external --no-build
          scripts/generate_source.py external/Vulkan-Headers/registry/

      # - name: Diff source to see if anything changed
      #   id: git-diff
      #   run: echo "::set-output name=git-diff::$(git diff --quiet HEAD~0 || echo true)"

      - name: Commit changes
        run: |
          git config --global user.name 'FooBar'
          git config --global user.email 'your-username@users.noreply.github.com'
          git commit -am "Update Headers"
          git push

      - name: Create pull request
        run: gh pr create -B main -H run-codegen --title 'Update to latest Vulkan-Headers' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

